### ISSUE TITLE
It is not issues it my question

### ISSUE THREAD

**Issue by mr-sakhreliya** [cruikshank25/Security-Log-Generator#2]
It want to achieve 10000 eps(event per second) continues can you suggest me configuration of it.

**Comment by cruikshank25** [comment]
Not possible with only running one instance of the program currently. 

The maximum amount of throughput I achieved in my tests is around 64 eps(events per second) per instance of the program. So if you set the 'write_time' setting to low enough (say 0.001) you will get the best performance.

You could use something like Docker and Kubernetes to automate and run multiple instances of the program or even simpler, just a bash/python script to run it in parallel. 

Bear in mind this code was not developed for the purpose of solely performance testing, you could get far better throughput for less energy expenditure with other tools quite likely.

**Comment by mr-sakhreliya** [comment]
okk Thanks
